version: '3.4'

services:
  telegramwebapproman:
    image: ${DOCKER_REGISTRY-}telegramwebapproman
    build:
      context: .
      dockerfile: TelegramWebAppRoman\TelegramWebAppRoman\Dockerfile
    ports:
        - "8082:80"